apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:lTHgRN19CfV9sczAbi71iZW17g==,iv:W4wW5N2uJXje62VVfk7uHCACUATQA0NulsBje8BWJfU=,tag:RcspyDS4W4arlzouM+grAg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:HFMfYFozkTlRc/X3UxutGD0nHqMJEpQDnMlB7x0q6vReqFTMxg==,iv:JVEoTyD1/Cht7ylILM/4LU7dDAX/+ux5ovaUS2yE2pg=,tag:Q5cLjzGT+BFET81ETrsO8w==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:bYUDVhZ0qjj3g3e+OgMy,iv:sSviq11i36WQbsR7Tu4b7+Omx96WwlKnuWVjcbZcOE4=,tag:b6NwUHrADGsXTvym/Ue1lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnM1ovQ294NVJ4SzVIbDQ2
            NytadnJxdDh1N0VEZVNrZG5IcE12czNRSkVNCkdwaVRUNG1MTDFXNzNFVW5IT2hR
            cXUrSnJRWSs3MXBpUVpGd0tWdUw1ZGcKLS0tIDV4ci8zMXZGZkxYVFJkL2VsL0Nt
            SEtXbHNGR2xMRmRCQjhOTE05WHE2TlkKxxInLZxsz+6iSMvi9VdD76nXpps81vv+
            5nWXMhvt62qf1WVOs0kAsfqoUW5Qx66wBC1RkQzeJrLpP3zQtAPXIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:vxNW+i1i8z5mpX2uQ1c62CnVKJSa4W9dUijT7kxJ7E2QmcNrB95kQ93IdGpayL6b8NLzoDac7QC8qlNQ0SjBhXsvrFMlMnYLaY+2WIF554dj8J8f2iwb+tl2ZOQoPo55N5qOYvmPOz6dVX733haWdyFxYobqyke7k0I2ZdlDrGw=,iv:eUCLHS0nlswSu73kD/9j9J23g/ZamDkuVtOgs/09n0w=,tag:CzUxitoN/bodJTMj/fv8Kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
