apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:yRJceVJS7PQGVIgThnSq97xsdA==,iv:uWkdEc+d7rq1KI9+qbjZ0ahqKGLvw2I/XCqfOj9pkus=,tag:G4Hrfk8UMQS5+nC2NjUOrg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:WYneBkNr69XCZ4PQDkbCaAOSGe4sQPJHxZOWqMxfRmFJU4PZ9A==,iv:tIcdzAowPYqVMxAYdp2t6tJnQJO0uGThlR1ZNnrbERo=,tag:pSZNQghcANX7g2Kap3ESCQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:xKU44Vk+Su2DkqUeme04,iv:j59F1Lv2p/9g4ZlVB7KrF6nhwjzh20krIuuqndu4cfU=,tag:SVGkwm8k8qLlVnO36zjJBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4M1VGQmFEclJYRjJhMFB0
            ZVpmNy9USm1IdGJzR3JNQTBjbXltR0dJdUh3CmZHMlpDbVE5YnFjVjBTRDhtSEgz
            ajNQelhaaWd0Sm13RnpVK0I2MmJGZkEKLS0tIHNqWFNucEhUd1BtNGtQcE9FTE1y
            eDB3S0xVWDJsZXJvT1pWRXJ4NkZqeU0KceWt/Sh50EYwOimqOabI1fcQKUB+PQsf
            bovSiZOyEYLxRBNccz6VYuTxY+gDcUoYIQWyBE21LGAtIWTuedoUbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T10:27:07Z"
    mac: ENC[AES256_GCM,data:rThfprV+1m2oa71VeuArHMi8z5/vyA4njNGumrpU4zZ9vvkOeunJEWJYKDcqy1RRrVJ748WvpRI2kUWjLjFSHWNa8kvE32tPjjq8S/yxE9rHN2SchkxS5hze2lN7+8oj9YrMVrxok1IZxTLV9h7MetELd3YiS54UNGu+WWz1byk=,iv:h8w5VErmOArOBpEnDPR5bNkTYOR1ZEWPqzcpc3MBAWc=,tag:8WleucCylHenj6CNGhtu/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
