---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-namespace
  namespace: flux-system
  labels:
    component.cluster/part-of: definitions
spec:
  path: "./kubernetes/apps/rook-cephs/namespace"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-operator
  namespace: flux-system
  labels:
    component.cluster/part-of: definitions
spec:
  dependsOn:
    - name: rook-ceph-namespace
    - name: monitoring-kube-prometheus-stack
  path: "./kubernetes/apps/rook-cephs/operator"
  prune: true
  interval: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: flux-system
  labels:
    component.cluster/part-of: definitions
spec:
  dependsOn:
    - name: rook-ceph-namespace
    - name: rook-ceph-operator
  path: "./kubernetes/apps/rook-cephs/cluster"
  prune: true
  interval: 10m
