kind: ENC[AES256_GCM,data:W0a+6eM2,iv:s35tUCfK1EMqid+HeDSN3+QbXs5imi86mS4QIb+xKfE=,tag:8FCZKM4z9lg2gj2RwoIY5g==,type:str]
ansible_user: ENC[AES256_GCM,data:Dbp8,iv:u8u0WaWjSGll3/afxiaXjs+d4XMTamOvm+TY4yEHOu8=,tag:+xllgI85OW8tj1VcRq8y7A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0jNBkF3wNIk=,iv:vXL/1pTCwHQ/1/kBxxB1dDkg91/ZJrpCfOtaUmGJCPo=,tag:l+U7B45w3DR7APwM56KBFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaU9ZNHVjbGxZZ0M5K2cy
            MnVBZ2l6MWoxRXlodEZmMEtIcmJETWFYdlJvCnV4aGNuSFprYXhTeVdqTzFEVTVt
            M2lXaGJnUUt5R0hycEVoc1NrSHAxL1EKLS0tIEhpT3BGbGp0blgzTjVyWkt4K0hX
            R1U1VjA4QnExUUVSVEU4M3Z1bCs2NjQK7jUl7tmPPqaY9ZS03l0AiEgNbaYahn14
            HUkOhRNqbaGRtupSgLRTSwjs2s2iB7sa40FddX4ijSHomwvEVLgW4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:WDJNHrQrsIsLbi++xr1YuucbbK/lUj6cAajBNusdLrXRlwCJF9pz1MCwxXyeKIul4RSQDSzHD1tElYPL1xEjK+o5U+l1kVWQii9qrKSIN96U8hIF5w/b3fG70u2Cp/ELcf1JkrFWChQNk28zczaaEQUIBMxzMii6QJVaCeUc1oI=,iv:VDu/vQqtF0gUoKqIaAPUFySmzNhpjVCek/QlWpGOXAM=,tag:87dtorXrhtAZEc4Lee/bXw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
