kind: ENC[AES256_GCM,data:f/BFClfk,iv:qKcnjLDlQQjaNJuxDZzT7oA/sWtcRaNXu35CWjGse2A=,tag:mHmKZK8d8tGM3PD4N+JLwg==,type:str]
ansible_user: ENC[AES256_GCM,data:ivEk,iv:msvlRnAPe2periX4+S0md08HvPXvTC7m7UL0A4134F4=,tag:2b+R9xBc2a1I5MFJQ1xyMg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:YzIpjvDip6I=,iv:E1HCtPpP6t+ECg72bXyuv9yhP+8UwsKwqJrfvqVQNio=,tag:331zYNS59l+Q5aNqPXG/hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcU5XeEFQQnFPSkp5SEtO
            VUZxK2hMMmQvTFAzZ3JRL2cwT044cW1TOGtNCnlYenladlI0dGE3RGhBeEc4N3Iw
            N29HRUdSb0prMEFlOWpVaGRqdDhyeGsKLS0tIFVMQ29BdjZOUDhBMXlUY2ozQmV3
            b1IzVVFDUUJreG9ZNTZuY3pIMzRnb3MKT2uRcl/BBWce6WERtBx8Zg3tUxTAD4IV
            a6UCVHsZ6fhI6gpAuzEE8v4e0EHjlWKMUK1c6T+DsmOQ5Tgn3VwNWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:7DtCGhNKzjloQZNVtEyn1wMwXrGX1kN6kyEY1FAcgehtQXXihz0pBv3z/18/8HcNsh8fepbpvJvoVSoXG/e1zicOFl2wRx6lBVMVnz9PcnMS0TbWWTcaHpdnxCFsNIAgKrxwTgs0B68ZPtrs43ZbR+msGAABhSVHA2wX+2sBNjc=,iv:xCaC6HV1COHTLEJra/sY0WdnM+6xoQ2LRLCElDE89fQ=,tag:sq+3BMPbCMxLrLoYCA1d+g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
