kind: ENC[AES256_GCM,data:Cdced0hd,iv:gZobWgVocLq43abG9vLOhcUSxv/z3dE8FEo3GWgf7cM=,tag:hJewSdPtqg5GaKPOqfifLQ==,type:str]
ansible_user: ENC[AES256_GCM,data:bak3,iv:WT6ocANtBjkqoLNKIeKGvHQIxJDPKuWc7vpqK2OPNas=,tag:l8wqam2M0cY/wQ40N4Zf1g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:G94JUpnnNhE=,iv:ddAbmC+9PkHuX9sZ9nwAe6ji0FWC1HQhaLEC1JmeKso=,tag:FRQ9XQ5Uw/oAiyHnh59dGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWTRlUk1oVnZ1RkFKVTBN
            azVlemE1QXY5bkM4MXgxUEpTNzZWbmVSelY4CnF4L2FXb1dGdWtNbVhadGxuM3l6
            WndHajdEa0UxMU00NEVTYTN0L2VsdncKLS0tIHIrVHBwYWdISlV6MThJRjM4NXQw
            eDN0bEg3TVNKRXl5SkEreUlxeEYxcE0KYI5RLfpDw858mPWe0qGQuYmQPmyFxeW4
            0qfVpKGA/PjCxCwfwKM1so5fPGapJSAxCD2V4iI4iukeXHZgmOmrJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:tp0yZ39TVxZEHHZ+FHXiJCbFAzraUVtvqXKOUJBo6o5ywiQZQbDmqgLpPC62qYKp+SUE+3xhN9P4qhxYX08VtmvwT6sytOJCF0AIrLD7NuMYbcNBqCCDxjnGEs7ixYAEwakPVenfrAqaorbk4ycJNtbNrVOsrcP/tUDvJQ7xV5Q=,iv:2I3jRfKqYU2tQ1i5EoxKxeFnaZOOzKUAikXz1/9yqSU=,tag:wu1V2LLdWw4lrjdrMaJQcw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
