kind: ENC[AES256_GCM,data:1IMmp9Rj,iv:3F9/WZZ7GMbmSV7xgFmtfE0lnIOZAPepzEEvAbhlJN0=,tag:93bvDXlDZ8d6XJTDL1KP+Q==,type:str]
ansible_user: ENC[AES256_GCM,data:iA3A,iv:X4HhToeSHYtQaKMuoNk09+uWuPSsXsVxB2vV8tovt2w=,tag:YnsSs/xCXPIjgqqPg+zJoA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:1mARFOSIqLA=,iv:1XkIunWns6talU6WvF05pbd8+ECsAe6aQaRopv/i3is=,tag:FShbQNDSM7c4cc1uya75tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaTAvNE9lM3VKOWhDWFQ1
            Zk8rWGVLNEFROHl5cHEwL254YlBQd3NRUGw0ClNINGlQUTdpMHA1SG1HcC9aYndM
            Uk85ZE5zaTdQSzBlU2cvQ21tY0pBMWMKLS0tIFFOb0lxMkh2akI5SmkrR0docmJT
            blRzUmthODN5bElVSDR2QzVzeXpYbk0KLoxEHuU4x4Py7DBihXIWDCFBLa1GmRQ1
            Nxlibjx5iGxVM+K5muM8Jf5QXxwDDrU5Nv/M0AuyTFvzEXfu4n+Ljw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:G6viLjWgVHpN760NFWTdtl0eQIUIMDqbTYzrVUEDij9iDijA7gitTb9+Zud4/+Y9AJTN3jgVhfTOo+Oq/5LoiL2/RHGLBPQPMF+VF8UwHhpVMdlZszDqktbhV7fCtGclzPnSXAR5EwD/zrN1cUiFeAVICs6WrI0dHJFXjyqSzlI=,iv:9D9VhA4dozmPUogOjEVXAR8SiYpoI9KF/4KmuNfQ11U=,tag:w8/EQtlUHVckZbT3R31HgQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
