kind: ENC[AES256_GCM,data:3c84/lND,iv:96TDEsD9aG+X/J07FIqvBR+9cl2CNAanLKkwHqfsAl4=,tag:YcSsInR9N5ttn6miQosMHQ==,type:str]
ansible_user: ENC[AES256_GCM,data:D7P9,iv:fzEG/ZWDKiMJ7TuyIY7EYfyDgdjV5DzpVvu2bl+qols=,tag:ffO2KFHVp5ES4vicR+pK9Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:tZZf2daSuI8=,iv:6mFQrfo0sSclwBstpALso7WzEb5NadRCPGOaHqtVPYU=,tag:P1JcMl72DK3GS/yqYQTyVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WnZJTjFwai9Femw5SjBO
            d1YyMTVpT2hSOEd0QnY2NWQvTXUraVZidG00CjAxTyszMjFrVlFyQ3NYV2lzTFBt
            SU9iZ0dlMnlHcnM4NmZndlFZZFlERFEKLS0tIC9qSUxvdnZpU3Avanc3cnpHWUx2
            b2hoQS9HNlBPRE1IbEVzV2dKd1Q0N00K+csAjGUaKtepwh8n+t7lNsMEF6IWlHDT
            h+KKuLe7ZfsHyag1Avpkb3hm9kjHhz9ZkwtQCWJssaTtsEIoZPkLHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:8O4dvd05sFufFnxTs5iAWc8boOXESuJJislbhk2v+t6aKIAd12keUJALHXKj1Swa0Gt1oiHvlqjmQ+/WsFJ9WWWPnw53fHuQ3ceOY6OItlTPU1JMaWJ75FRDNsxOwqu4HRxAzrFT8IX+YSl2hooojPHaExrDRZpK3nrG40gSeeA=,iv:nkgn4Lm+XAH0dFjs2/RHdM7YiuKPC5RuRviH16pssv8=,tag:AV0+7VkmcjRjpDiQ9FppqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
