kind: ENC[AES256_GCM,data:9V6dkmhb,iv:/QjaojYU7ej9l7bghcDh8nUrLBSCCiO6RdYCblqr2yc=,tag:p3D+CH+K/Fs3cozJgPGS6A==,type:str]
ansible_user: ENC[AES256_GCM,data:PfD1,iv:I4JxUHLkQzEaseg1jx7V2LgXD1Lfg1cxp6v+LE3jDd8=,tag:qSux2slmJdrqS+Jw8HJ85Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:e+8A3FQSaOQ=,iv:PL22Or/zbYxyK0Ae9bhh5X2drXkioEDNlxjBxD9O7/4=,tag:MBipy/Pl+Q+B8lZixSYi0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdjYzMEk2U29BcW40dWdX
            Um12cDFSRm9DQitRRjA0OE8vb2QwMVUvekNvCnVPMG1LbW9TWGRVOTJTL0tOTEZ1
            d3RHd3U2MnpPWEQrNUFSYlY5RXRDbkkKLS0tIDEwNnZIZHJPS25xQWx0MHpHZ0ZE
            M2Y0dzUyTVhUZWFVTi9uQjNpQy9KRFkKhITEs76U7nu2CenW0/sulkO7F1MaRike
            9/XgZcA+cZ3dUoqFfoFZ4HCHMJSnz055FYXMTQk2yVs3lsQCaiHH2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:GJd/NwH0pIe7wlD9wJCdKYLH3GeqgI1Lkb5vqQxctiBJeyJ/SserA+JPql+xyyrOvhHVQwRISM7IVwf8WAiOKEEpHOm5h4zrXhpDN1AHOZx8C5MAJZM1DpAYM4l0W1EexOHnmpsbTLBHAdZbLA3CW1M4cNidkAemaYBcDQWY/yA=,iv:ZwEFYpvwnl6hD3sIcrTTz9GB/b0VzjSPaNu71xKnrss=,tag:BX9paCWo89X8wMRN+BdBmw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
