kind: ENC[AES256_GCM,data:+MFZdYPL,iv:ncd9db89U/XBjEYUtyARW+I7xNHX0l98KaFlIqY+ijU=,tag:YAs+h/Yqbj67vrIbnUa6Ng==,type:str]
ansible_user: ENC[AES256_GCM,data:WJ0P,iv:RGnQjxTvTnonztYIf0YtGZXaQcLiBzfk5ijyshUyhwU=,tag:GPGKh7plk+X22zVlXIxYzg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wN9zsP9hVYo=,iv:koa6bRPEXXpobjLy6GI+QTJMP0+kphP0Dgzy3pZK/d4=,tag:V2kWd1l1DbhXa6BqrcccyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QlVENEpOWDhMcVh3S0ll
            M1V3Q1M4WEk0UlhuZC9uT3JDNXd5d0duMW1FCituNVlpNUJXY1hUS3lTeDJUVko1
            eHl0UlZvNzZzZFhHdm9mZXRkWEE2TDQKLS0tIFZhQjJERzVNUFVxWk1CL3BiZDNz
            b0dFVm9temZGMjNpd1M1Tk52TDdTdVkKirmS0NduPAAtnR9l+m1YaK/ksGQdKlC8
            8SI/rRmBaH61lqYA97OKto6jVaH62sefWp/8tBBVaFhpskXrrPteuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:iZjpYJqDfB4RWvYNzSQGgZDVRIa3Zo+IxHYFPXxRmPguUyO2a/p3o6BJe4+wAzvnkQBHEDfvmo2+gcIiWCMRzu2Muzbzhx2Jn6Jg6tYR2k8oe8/rxk8cvbYnDOc1GLygq11rMKjXsugEN9pKTOOfjOt3Y/azyeO3iAdLbBgqG0g=,iv:svmeW9Kf+J3My4JxrtDvDrzzxjFajYSUBPARHcdqGjo=,tag:iiPOE3QAytESC0RdHPYN1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
