kind: ENC[AES256_GCM,data:Qen6j4Bu,iv:Vkr3+YKBmeqPOcW7RggZ8c3dLZWTCk726cwPdhlpLF0=,tag:65JrAhXePRsZHdiqPgnUmw==,type:str]
ansible_user: ENC[AES256_GCM,data:Hdeu,iv:reQFneEZTRXBEe1BaGl21h9TVWC7svPv7qgZ9Y/Qgrs=,tag:mbCMsscTvGzhg9wm2Wg+Ug==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ctuSPvE0oVg=,iv:BfQWiiY7mprmse3fhHJkpRRSBjwfcB3ADksjH9idSRA=,tag:PHAyhUJzRXYdPMk2YHNWAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYN1JLeWNGQ0hkVXhaV0kr
            aHozb0NoTi91S2cvTjEwZnRNa085K2N5MFc4CjF0TEJ1OWxaRUhDdGZzVnNndjc2
            VW1OajFoUkwyaUgwRnl2KzVkWHZQU3cKLS0tIGFjZGd5L21kQzMrUHh4NnQ5RU52
            K3pnQzFUT0d5bGFPNGppNGZ6U1NLZUUKdBpNAIQ7GpgZRBQNpMA7fEm6C6FfGRTZ
            Squ6y7dTSyyRoqZIRUHH8Drw/hq7h6lM9We0nfJzQtvYnMmDVc9aEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:8EhFEGLreu5DFYK1PVuzCifJmF2Tz0CK+gxEVy5HF1MNcdPcCw5bdMbVFNfZ2c6iziwhBJqpeTqETrHnPtR0EXUu+vWuZZT9krqiMSF5djSjkftJ8+ir61OktK/S6y19znnz15RevE4PIaKK+9uz9ugl8SPHulCyhkLq/iiYDoU=,iv:AiqoDnn8tJn8i73rvB2EykfC/vCn3ghxqXhj5ltwJuA=,tag:nqbD53FUfqhOLHyrKn99Gg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
