apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:RZLbZWi2ZJuiUw==,iv:CK+IDS8quFfDjWKVXgxKpZqHinY03sIpzNOo2KwPuqI=,tag:+zpjZEAAgNfGmwV0l9ePFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN0hxQmJ6YWprTjR2MUxj
            SjVDRzhtVkRmSG1iSEoxOENZWVk1RVZwNnpVCnN4U1dyMDZWeGhWTy9WemhKRVRk
            OXp0QTlCMTN4RU9PV2ZJNnErTStjZ2cKLS0tIHdML1pkRHNmcXNMQjNmclpTazN5
            elNIMnhZQUlDbjVXeFIvNlU5ZCs0YzAKXUWqJg5vNawDt9rj+fpMvP7jGn0l0ytf
            0S5E/vNNzNwuFlNYo01GTE3V/ydm6TLl4gzqaUlXgUbeD/2LeaoFwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:6YaVtKDn168e5IBcC2/j7UZUaAYHD/92zP1lTQPPllKW9qwEFwCZeQ4b5kIJWR+iMR7q3oSMNXEKVYvviys7u1feGwwR3uvXeDDAzYqNj2N2pDaQ6PYIQRmVBsug21GTWKTl882X5+bjYJIbFLyGOZvfq3lsuB/T4GE18mrlxUM=,iv:QoxB5QZL/4kM/lXGJtcgJpFm6yMBJCl9MOaOVJx8GoY=,tag:nikJW7uoKFMFL0Dr9shqXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
