apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:fmGdmq4QD0NJDQ==,iv:M5bgSAXtXUvu6MpAiT4ZU+hGB11lMkEk1ijb4Ya7SxI=,tag:EfmDzUReNvZYFgOPqHEv2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOHJjUHBRZDU4NVI4eTk1
            RENJWW5WL1p4U08zN05DMXlYNXQ3a2pGKzBNCktQbmNGTnpMb0dtRGNMV1FZNVpo
            U2xJaHNIVlNURmpNVzNNdjIzMGt1WkkKLS0tIGQydFJLUEgzWUpjYko3Z2hucFVl
            NWJvRzZZbUMzNUhVazEwYmhuWlQ1ZkkKR5kkplWF86mAVXlMpf/AR3uCqonHgzJP
            B+VTngx1/4cvSxA6mXbiaBoxkFdto3L/uOHMpqt3DA1UzzrZHRpL/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T10:27:08Z"
    mac: ENC[AES256_GCM,data:0sGrfAVUyOte2MiCX6jAEZqZg4IH5b/+qMfzG5UTLvLsD8lOY5N6rDDPVwLxeg37eXHzBXjh1CuztFwDGQ3iteBCiGx5q8r49LCFfOuEpB96faz2wE0iJCld44l8m2eDT/henZsw00ngIzlC6hxGrzb4e4JQnY1Ru4m75Zrt6bo=,iv:7MOJkzLA8Q7IEQFXV7mdJWh+zbO76LXm1kMx98z+r7c=,tag:YqJ5/vn36wJ3Rw0dhvcWWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
