---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.0.22.181
        k8s-1:
          ansible_host: 10.0.22.68
        k8s-2:
          ansible_host: 10.0.22.33
    worker:
      hosts:
        k8s-10:
          ansible_host: 10.0.22.83
        k8s-4:
          ansible_host: 10.0.22.30
        k8s-5:
          ansible_host: 10.0.22.205
        k8s-6:
          ansible_host: 10.0.22.19
        k8s-7:
          ansible_host: 10.0.22.17
        k8s-8:
          ansible_host: 10.0.22.247
        k8s-9:
          ansible_host: 10.0.22.228
