apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:O0AOVoiXKWdScbvOD1NHLzBFpUyH7DGcnul0/G+9zc6P1UM8ew==,iv:Apl0SLGNco2motw325Nb+RbIPjBApNmU4VhmV8m3nkk=,tag:Q3zx5eKr4dntYEaF+YSXfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MWRqWDJnbFVLa1h5RjlD
            Wkp0MUwrTFFBOXpwK3l1MzVoL3YycUZuRlJFCmVDYUtiZC9IamliMjRpcllCeFpz
            VG5tTUhpQng1a3d4RmpVcDZWQklwN1UKLS0tIGhOclVJY1Fpb3QySVhlNklTU1Js
            cHkvcHJUek9sYldLc0VaNzBkUC9TRFkKTDaaAi+8rZH8JVq+bjKoPHvdDhq3F7p0
            4cY32rlMatOyOMorFN3NDOIMdUWIFdGniVAfKu9i1b0sVi5OyEa5ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T10:27:07Z"
    mac: ENC[AES256_GCM,data:Cs2KX/7Wgd/WvU0ywQopesFyjNfK4OcreIORyGWCd32cSoXQGpupGffRhf7Oy44heFRnjeLXmNGF+Tf8nQHlAbpZ6OmLZI5hkiVBdq3eXfhBxl3niiB7AxzDqZEJ40Hwvy7i1it8/CI8qVtSaFRyTkMBGxvi3TkR+2RS9N3CQ9g=,iv:aD0/KfKTHwUR1BH0QDxa3/eUPW0GKEPrf0CwoEbq8G4=,tag:LOEXvLx9Oxd0uwATNBxX/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
