apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Bj0UwBC/cX9vo32AmAYvzkBxjlHl5KU2qcvml2tJ/9gAsiLTNg==,iv:ummNobIOWcc0qovkeVKB/rS/ZzVerzZdsIcYX1JGqD4=,tag:Jgp1fa6meaPGyjM9T9gHjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd05pMC93bnN5WFBhV3VF
            SkJ3SWFhaGxJZjloMm9rRGFPR3ozMjRWN1RFCnBEK0NTTStzY09XMXlUalVIK0w5
            eTI0OGlMVnZSNWtjbnVrRnV6b0JOVjgKLS0tIGVMcWNtQXIrNDVlNzFoRjh0SFJQ
            c0FqTCtVTC9rK3FPRnRTdVVOQXlweEkKRPNl+IMAYnO7jEYwAXbuuOF0+6VMXWgz
            EUOi0F9wTzQ5uYHpEgiXiDlSK2xupxZTXnl15GZzbosrBDqsUlfR6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:EKKeSedzk6Eau6nm0FEJ4kxTjhfzmvN/Mq4421lQCqA18yPk2JU2+8LtYpdTV0Gh3njKX/6vo9hvyzEuvSY/uQR7PSgn/HnqfTsoQvMdtqRUQoJS/NbYcMATpPsyq4crcQJHgjyAT90ahd3ovBMBv6G0HMgrTqrjvdAC8qWaWHs=,iv:0tvp0YwvgDkPec4BYMryx8Fi9hblOSWhtJ9GBcFiuDA=,tag:d8zQlgwym4JiuDShSYtF4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
