apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:54B0UWw6wETUOUCkE3PgUdlzww==,iv:4qHOUd4StY3t7G221jrLas4tviZm0Nq6EfKci/vP9FE=,tag:m60+XE0PzUMgDjvg45MAHg==,type:str]
    api-key: ENC[AES256_GCM,data:L8PxkYbe3bxHClIjIrum0S6fzhTAe9DuSa9PiZ3zCCWE/zvcfw==,iv:xsfAP5A0o9sVA7L66ve7lP11CaNTlVu+FSoZ8drJVHk=,tag:gG6/go3ZUnbbqCuZwumH9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWFZEOHUrYWRCSzFnNXE3
            L3Iyb21xNXh0REhRekhKcHBoeHRISEZHUTNFCmg3T05wR3dKa2Q5aE1MUHJWbWVp
            eG5JSjVjSkxNSjRUTHBzNGxHZ3lSUm8KLS0tIEdLRGFlZEozUHZzblA2MWEyMm0r
            Q2xxV0hKWlJhcWRxU0NzSHZTYm51ZE0KM+aZhqo55PFMQwJfXxc+mmAUMgZQh7gm
            ThMdOiN3bXHOOaYIWu6i/cnd3PaFEqM8BA3e5cTmsCxj/f6H96biOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:l1L67/G0zlaxCHgAtX79YYhFn7e0aGFE20i4bu97xFZXsNQ4Dh8a/R+C9VrJn9Q/7NAslIpLDrEBQFHhPltTEirfqZwrmVg/nylvaGrabKqDgYIOnuGd83kradqY4brF03gDPz+5guBxwb61vD/af7HDbO4EMAzBK/5jTPQ5cFc=,iv:/7uDdCY8t8iQAnfGlbwCLiOOEyboA6M6sFQXYD1CgLY=,tag:Wxk9A94oN6m3avipI1Y1Bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
