apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:hOzdilxlEGxdd8fWI0M4YQeTYw==,iv:db/o/KrRLSiUwClRnNAAwBIva3Jh37djXT2Js101tto=,tag:knfKHZazZSJktgKdGM/tHg==,type:str]
    api-key: ENC[AES256_GCM,data:+o4nlP8xJoyPe8xh6/gp9PRCRvEup3orQBfIFlbUDX3tuPE2kQ==,iv:yVZluYIc4EGdFINDIBdcC9hEcIv866VODZECoPAkVJ0=,tag:JBxwKj2nuA8gxCY92hErcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaHhRZWtBUE1KQ24vUlBF
            VUxSamM4NEJsR01HbVlZbEJrV3lUU1Ayc0VZCk5MSU1jWlB2TnZacWdrVnpZNm9Y
            QThzN3I0T2RId2NFOGYzbVZsbStlN3cKLS0tIGNzZFFzeUd6Z2F3UE54QWExSEdi
            dnl2bURkZ2NuRjBSUTMrcU04Q1NCMkEKuyiq6j9gr50Cbzy1MHL4IcKxCCrQN+0e
            ID0+K4IwkAtJTirD4lT7d/oWADq/XTNnDWNZYyA0bR9kABMykIadtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T10:27:07Z"
    mac: ENC[AES256_GCM,data:CzSCTy6zmDPdEoD/9gwe8H+vhr4gBr+sb6o+NxtSkjj+vMhh+MDCaB1rKYNKCDrWgGB3Jl9NQwJKXcokev9EMKbee7BK0jHtSx1ETa55RtEJtzp5EhrOXAUC1K3SfY9horI3JQb/UDzkludgSJKIStiED6CdKEvJ/jJIhPMbAwA=,iv:14yWNRRhhGjZyvD0e47a4q+n29m2uNyYTltRi8SlC3M=,tag:R3UGZp0VWpBsYvSkg+DH4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
