apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:9NoGg/48Ld9Xl4dSjUCeQbeI5/JQquTWiRzBklZu0iWupF2mDaPF0eNmb6Pq3OcxI6vkdj2AAJv+quMJ,iv:FVMWBEpWB+hV1mp6hnCIw1NVZnsrWNGCtCSCR6pbK60=,tag:O/F14KJDQrvzB93g1iHF6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcVJ0NkVjK3IrSFV1SlpT
            ZkRKWVR2TG5FeGk4YVVyZTVNSmw4ZDVPTGowCjBGajB1T3oyR2VNSTRmV001R0dH
            VG5rRkk1c1l4M25IY3lHU2UrblBXTncKLS0tIEEyNUVIWHkwelEvU1NDK3RFSTUw
            VFo1MXZEMmxQVEg0bVFCdERFL20yUzgKpoCd54FT36Tex7Wd9Lyn45n44sa2SXP3
            xqGGZkpwv/47a3Zx2XWIXEPwp4nxdCtrbh1WOZq9tYmxFJ+HpaiChA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T10:27:09Z"
    mac: ENC[AES256_GCM,data:LgernEIzR/+WtkXbrpF7HsienlNj1ocfaA/zbRA0uIzpnlgP7XkJf8YyClw0SKg94dt/6NtD9OzInN2fD4VqhdvqPKX8ak1uXhySj19hYSIK4lG4o8QRfraTcL5vl8oKIfNgHqFA9ZpMPkHMtbbf+tlVv0umQKhcap9oUvqgyt0=,iv:ey9S6SzcVV4P8X+a+BGefgMr0meLC24akekEJh9/h2g=,tag:VQNM1LTloXCYsGme9UKdKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
