apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:186Crgw18/buDWMl5qD0ld1GA+RbjKyd4rbZxFbbNzlQ6qYj23sHB8G2qE2RDhe5jLt3bUMRJwNvDLPv,iv:ngmYZmGA5m9ZlgFEvWV3xgnlu+rNMwi2/HS+FQpWTIc=,tag:e7QN77In+obXn//3sRIgCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR2JVTFRTTjh6enVGUDlu
            MEExb21MQVMzcy9UakVuSlA0aVcwSlJLaVhnCkdzc1hHUXl1T1FlK2xHWlhEdGRQ
            YytGZ1NnYlVYT0NVRGxXc0V0emtpcE0KLS0tIHJ5VitvR3NmN2MwMVNNN00zNWhN
            VGM2RTRid3JVMU9YaTVQb2hMckk5RXMKhNTs5IEMKKzat5LBM2OsvdTEu7GS+r2x
            qbgVXv/w/aGqCsBP467oZfA5VkeZv8vlYhGNXKJtqvMRaw5WNkIyUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:30Z"
    mac: ENC[AES256_GCM,data:UF30cM3iNhdIsG9Pnyxggj6eNvcGQ9NI2cLHfTFOP5ixtOR3hwA8C33DiCBCb8ff4qrV//RMFo6EwxEPSfeDIKgeBrCR3YfJnl3RWlu+gNmnDnc+2Zdn6PrEVrPOUb6LqoWi73g855UTQtEmjxfKpJIIMA9ZaTujSWPheoHhUx0=,iv:Uk4NIqHMs0VUojOD1jYmRly6g7OJCKyx+eFKBmcGvXE=,tag:xglv7XXKq9yG7q7iL5C5ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
