apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:djn1IIsMeerMCQ==,iv:2mZxu5DNIEufGUe8xnfFGzQjmzModc3WJHJU+mOMDko=,tag:cwsdn0G4ccprV2PDd5g5Fw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZggFwqbqx3W/wCYgSjmPoyZUKw==,iv:Ut5QjSUkCSJssePjRD8ET5InHgfHF/gEsJT+7tm4wG8=,tag:HyCTz6aXhb00RzTVnzhRrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaTE4QldvM3ZqUUY3SGg3
            bVJvUEN6M3Vjczd6dUovV21TdXpvNWQ4L1Z3CnRnT3dUTWVYNkRrZ2VPaXhKVWNw
            ZDNzclFhWkpXdmNUSS9lTlRpVjA0NGcKLS0tIEx3ZS95ZDJsUGtnMXBnZmduME84
            UW1Fd3Z4aHhGUUdQZldJbW9vaXVoUmcKUugFm6lO+Bt4gS+2eeBMi2bcvauzvz53
            ui6xcOXK7T0PSqwRkosWFvb/3nxECH0S0JBMULlGD1x2ZV12s7YviQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T10:27:07Z"
    mac: ENC[AES256_GCM,data:6WXRIiYnPJyPHh0B6rqvPreZTA3+MccXrW0BR0vLJWBfbnsfliYkxny7IBCFrGi9siHshTT8gndOc4zPc5UpgIJyJRammkcJNs8rMlvqhwEEoUTDm3t4q+G5oMtBBIryOhQa1WRBugutdavTolGrKOjG7DU5gUNk7I0gOP7IpYA=,iv:4T6/DUSKCx88YTmulqczjYg3CGZLl2W86QyPulKQ7MY=,tag:gMSchHmCoCxtPOEQ0a/sUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
