apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:v3+ielYVuORzTA==,iv:ufmN/4rYmsHBniszTMUGPjU4LlW2DwmpDOCY1LHgzk4=,tag:CAL4hv6h15eeIXO6IyxEtQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:PY2Cbi6xbQgSNMcbmtW5YtCMGQ==,iv:2GQ8hbPo5b51XpvhwiU4mrZ1mAamBjJ6/fkLVADk9Pg=,tag:iD4Cu+kk/xT+tnD9VdLWvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUb09yNXR0ei9kMVE4QmpV
            UFphOVdad3NUanlEMHgveGRRRDJsQUVFbVZFCktnaFFZRytmU3RISkVvVFZzamNZ
            Y3ZhcHE5QW0zcUNJVkxleERxM3kyeUEKLS0tIDNPL2ExYnVlZFQ1QW55MHRTRHc0
            aGFHdEdkT2pYZFdwMEtEQ2N4SEdHRVkK2yqZLaHuzH6PzJiRwW1hIvQIHoTMJrtx
            cY3PCj6S2cdnm20WIhod2rgulUwHuFG+Gmh+2N+MpQE6kMPtVhhLag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:11:29Z"
    mac: ENC[AES256_GCM,data:HfJJMDm2XN6o3VtD8LFipogloE3Qbx01yLFDbc5/EN8MbvSCvT7TTmraM+JutceMDydgnom08um3/1n483Gzt9gu4mODS22kDD8oUAFOuvd8DZs+0a+d4J6pZFNpeDiQ+1cBsvP6TmxdvKbEiOmvbgGPN267DVnXQucaY4mKasQ=,iv:wiwBGgq8BE+VeBpK3G4PLsZwjFaXk33TlgmJklzuCzc=,tag:YgV0r/59gCPepA0Ny/WJZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
