---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "10.0.22.99"
  METALLB_LB_RANGE: "10.0.22.100-10.0.22.120"
  METALLB_K8S_GATEWAY_ADDR: "10.0.22.101"
  METALLB_INGRESS_ADDR: "10.0.22.111"
